---
timeout: 1800s
steps:
- id: build
  name: ${_BUILD_IMAGE}
  entrypoint: /bin/bash
  timeout: 1200s
  env:
    - 'DOCKER_BUILDKIT=1'
  args:
    - '-c'
    - |-
      set -e # Fail if any command below fails
      docker build --tag=${_BASE_REPO}/${_IMAGE_PATH}:${SHORT_SHA} .

- id: tag_latest_if_main
  name: ${_BUILD_IMAGE}
  entrypoint: /bin/bash
  args:
  - '-c'
  - |-
    set -e # Fail if any command below fails
    [[ $BRANCH_NAME == 'main' ]] || exit 0
    docker tag ${_BASE_REPO}/${_IMAGE_PATH}:${SHORT_SHA} ${_BASE_REPO}/${_IMAGE_PATH}:latest
    docker push ${_BASE_REPO}/${_IMAGE_PATH}:latest
  waitFor:
  - build

images:
  - '${_BASE_REPO}/${_IMAGE_PATH}:${SHORT_SHA}'

substitutions:
  _BASE_REPO: us-docker.pkg.dev/project-pluto-324014/docker
  _BUILD_IMAGE: gcr.io/cloud-builders/docker:20.10.14
  _IMAGE_PATH: covid-data-model
